$engine: 3
name: vRP
version: 1.0.0
author: SynTer & Plok
description: Fully pre-configured vRP server
tasks:
  # Download and prepare server.cfg
  - action: download_github
    src: https://github.com/synterrr/txAdmin-vRP-Recipe
    ref: main
    dest: ./tmp/vrp_recipe

  - action: move_path
    src: ./tmp/vrp_recipe/server.cfg
    dest: ./server.cfg
  
  - action: connect_database
  
  # Move and set database connections in GHMattiMySQL
  - action: move_path
    src: ./tmp/vrp_recipe/GHMattiMySQL
    dest: ./resources/GHMattiMySQL
  - action: replace_string
    mode: all_vars
    file: ./resources/GHMattiMySQL/settings.xml
    
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 0210252be7c17745fa30220e12c19e0d2f19af02
    subpath: resources
    dest: ./resources/[default]

  # Download vRP
  - action: download_github
    src: https://github.com/ImagicTheCat/vRP/archive/refs/tags/1.0.zip
    ref: 8eaf715e644c15d831d70bb3deb95b2eea70bcc8
    dest: ./resources/[vRP]

  # Move and set database connections in vRP
  - action: move_path
    src: ./tmp/vrp_recipe/base.lua
    dest: ./resources/[vRP]/vrp/cfg/
  - action: replace_string
    mode: all_vars
    file: ./resources/[vRP]/vrp/cfg/base.lua
    
  # Download vRP database connectors
  - action: download_github
    src: https://github.com/ImagicTheCat/vRP-db-drivers
    ref: 7a7f25c6db366696faf28aa77de7b4c385db96b2
    dest: ./resources/[Database]

  - action: remove_path
    path: ./tmp
